; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-p4]
platform = espressif32
board = esp32-p4
framework = arduino, espidf
board_build.flash_size = 2MB
monitor_speed = 921600
board_build.sdkconfig_defaults = sdkconfig.defaults

; If you use ESP-DL with embedded model files, add the .espdl as embed file.
; Keep file under this project folder to get a predictable linker symbol.
; Example:
board_build.embed_files =
	model/chess_yolo_320_p4_int8.espdl
