[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Uncomment and set your port if PlatformIO doesn't auto-detect:
; upload_port = /dev/cu.usbserial-0001
